### ISSUE TITLE
slide deck request

### ISSUE THREAD

**Issue by MatthewSchumwinger** [Pshrub/MKEBigData_Zeppelin#1]
Hi @Pshrub , I'm sorry I missed the meet up and your presentation. I would love to see the slides, I don't have Zeppelin installed -- is it possible for Pitt to post as a simple slide deck (not a Zepplin notebook)?

Thanks,
Matt Schumwinger

**Comment by Pshrub** [comment]
Hi Matt,

Thanks for your interest. The slides from the presentation were in the initial commit to the repo (the .odf file) but I uploaded the more popular .ppt file format this morning. The slides cover the Zeppelin product. The bulk of the presentation was a live demo going through the notebook, which is saved here as a json file. This json file can be imported in Zeppelin, and is the only export format at the moment. I attached the source data files to the repo so I would encourage you to install Zeppelin (it's free), import the notebook, change the paths to locate the datafiles that you downloaded and unzipped, and you should be good to go. Please let me know if you have any further questions.

**Comment by MatthewSchumwinger** [comment]
Thanks, Pitt. Much appreciated!
